version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12-stretch

jobs:
  checkout_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install NPM dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test syntax and perform type checking
          command: npm test

  deploy_pages:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - add_ssh_keys:
          fingerprints:
            # TODO: put SHA-RSA circle key fingeprint here

      - run:
          name: Configure github user
          command: |
            git config user.email "anton.dubik33@gmail.com"
            git config user.name "asketonim"

      - run:
          name: Deploy to gh-pages
          command: npm run deploy


workflows:
  version: 2

  test:
    jobs:
      - checkout_and_test:
          filters:
            branches:
              ignore: master

  deploy:
    jobs:
      - checkout_and_test:
          filters:
            branches:
              only: master
      - deploy_pages:
          filters:
            branches:
              only: master
          requires:
            - checkout_and_test

